lib/otaoto_web/router.ex
defmodule OtaotoWeb.Router do
  use OtaotoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {OtaotoWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", OtaotoWeb.Api, as: :api do
    pipe_through(:api)

    post("/create", SecretController, :create)
    get("/show/:slug", SecretController, :show)
  end

  scope "/", OtaotoWeb.Html do
    pipe_through :browser

    get("/", SecretController, :new)
    post("/create", SecretController, :create)
    post("/show/:slug", SecretController, :show)
    get("/gate/:slug", SecretController, :gate)
    get("/gone", SecretController, :gone)
  end

  # Other scopes may use custom stacks.
  # scope "/api", OtaotoWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: OtaotoWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/otaoto/secret.ex
defmodule Otaoto.Secret do
  use Otaoto.Schema
  @slug_length Application.get_env(:once, :slug_length, 3)

  alias __MODULE__, as: Secret
  alias Bcrypt
  alias Otaoto.AES

  schema "secrets" do
    field(:cipher_text, :string)
    field(:slug, :string)
    field(:key_hash, :string)
    field(:key, :string, virtual: true)

    timestamps()
  end

  @required_fields ~w(cipher_text key)a

  def changeset(%Secret{} = schema \\ %Secret{}, params) do
    schema
    |> cast(params, @required_fields)
    |> hash_key()
    |> put_change(:slug, new_slug())
  end

  def create(nil), do: {:error, :no_plain_text}

  def create(plain_text) do
    plain_text
    |> AES.encrypt()
    |> Secret.changeset()
    |> Repo.insert()
  end

  def retrieve(slug, key) do
    with {:ok, secret} <- get(slug),
         {:ok, plain_text} <- AES.decrypt(secret.cipher_text, key) do
      Repo.delete(secret)

      {:ok, plain_text, secret}
    end
  end

  defp get(slug) do
    case Repo.get_by(Secret, slug: slug) do
      nil -> {:error, :invalid_slug_or_key}
      %Otaoto.Secret{} = secret -> {:ok, secret}
    end
  end

  defp new_slug do
    slug = MnemonicSlugs.generate_slug(@slug_length)

    Otaoto.Secret
    |> Repo.get_by(slug: slug)
    |> case do
      {:ok, _secret} -> new_slug()
      nil -> slug
    end
  end

  def hash_key(changeset) do
    changeset
    |> get_change(:key)
    |> case do
      nil -> changeset
      key -> put_change(changeset, :key_hash, Bcrypt.hash_pwd_salt(key))
    end
  end
end

lib/otaoto_web/controllers/api/secret_controller.ex
defmodule OtaotoWeb.Api.SecretController do
  use OtaotoWeb, :controller
  require Logger
  action_fallback(OtaotoWeb.Api.FallbackController)

  alias Otaoto.Secret

  def create(conn, %{"secret" => raw_params}) do
    with {:ok, secret} <- Secret.create(raw_params["plain_text"]) do
      link = Routes.api_secret_url(conn, :show, secret.slug, key: secret.key)
      Logger.metadata(secret_id: secret.id, slug: secret.slug, source: :api)
      Logger.info("secret created")

      conn
      |> put_status(:created)
      |> render("create.json",
        secret: %{key: secret.key, slug: secret.slug, link: link}
      )
    end
  end

  def show(conn, %{"slug" => slug}) do
    with {:ok, key} <- get_key(conn),
         :ok <- confirm_existence_of(slug),
         {:ok, plain_text, secret} <- Secret.retrieve(slug, key) do
      Logger.metadata(secret_id: secret.id, slug: secret.slug, source: :api)
      Logger.info("secret viewed, data deleted")
      render(conn, "show.json", plain_text: plain_text)
    end
  end
end

lib/otaoto_web/controllers/html/fallback_controller.ex
defmodule OtaotoWeb.Html.FallbackController do
  use OtaotoWeb, :controller

  def call(conn, {:error, changeset = %Ecto.Changeset{}}) do
    conn
    |> put_flash(:error, "we could not create your secret")
    |> render("new.html", changeset: changeset)
  end

  def call(conn, {:error, _message}) do
    redirect(conn, to: Routes.secret_path(conn, :gone))
  end
end

lib/otaoto_web/controllers/html/secret_controller.ex
defmodule OtaotoWeb.Html.SecretController do
  use OtaotoWeb, :controller
  require Logger

  action_fallback(OtaotoWeb.Html.FallbackController)
  alias Otaoto.Secret

  def new(conn, _params) do
    render(conn, "new.html", changeset: Secret.changeset(%{}))
  end

  def create(conn, %{"secret" => params}) do
    plain_text = Map.get(params, "plain_text")

    with {:ok, secret} <- Secret.create(plain_text) do
      Logger.metadata(secret_id: secret.id, slug: secret.slug, source: :app)
      Logger.info("secret created")
      render(conn, "confirm.html", key: secret.key, slug: secret.slug, plain_text: plain_text)
    end
  end

  def gate(conn, %{"slug" => slug}) do
    with {:ok, key} <- get_key(conn) do
      Logger.metadata(slug: slug, source: :app)
      Logger.info("secret gate viewed")
      render(conn, "gate.html", slug: slug, key: key)
    end
  end

#  def gate(conn, %{"slug" => slug, "key" => key}) do
#    Logger.metadata(slug: slug, source: :app)
#    Logger.info("secret gate viewed")
#    render(conn, "gate.html", slug: slug, key: key)
#  end

  def show(conn, %{"slug" => slug}) do
    with {:ok, key} <- get_key(conn),
         :ok <- confirm_existence_of(slug),
         {:ok, plain_text, secret} <- Secret.retrieve(slug, key) do
      Logger.metadata(secret_id: secret.id, slug: secret.slug, source: :app)
      Logger.info("secret viewed, data deleted")
      render(conn, "show.html", plain_text: plain_text)
    end
  end

  def gone(conn, %{"slug" => slug}) do
    Logger.metadata(slug: slug, source: :app)
    Logger.info("failed attempt to find secret")
    render(conn, "gone.html")
  end

  def gone(conn, _params) do
    Logger.metadata(source: :app)
    Logger.info("failed attempt to find secret")
    render(conn, "gone.html")
  end
end

lib/otaoto_web/views/html/secret_view.ex
defmodule OtaotoWeb.Html.SecretView do
  use OtaotoWeb, :view
end

lib/otaoto_web/templates/html/secret/confirm.html.eex
<div class="section">
  <div class="container">
  <div class="content text-center">
    <h3 class="headline">Link created!</h3>
    <p class="subtitle">Send this link to someone to share your secret with them a single time</p>
  </div>

  <button class="link-well text-center secret-link-well fake-button" tabIndex="0" onclick="copy('front-element', 'secret-link')">
    <div class="text-container">
      <code class="front-element" id="front-element">Copied! </code>
      <code class="back-element fake-link" id="secret-link"  ><%= Routes.secret_url(@conn, :gate, @slug, key: @key) %></code>
    </div>
    <div class="center-vert-container"> <span class="center-vert icon icon-copy white-icon"></span></div>
  </button>
  <div class="text-center">
    <p class="subtitle">Want to double check? You can see your secret one more time if you need to.</p>
  </div>

  <div class="secret-container text-center">
    <input type="checkbox" id="show_secret" role="button">
    <label class="button button-primary button-outline" for="show_secret" onclick="" tabIndex="0">
      <span>Show the Secret Again</span><span>Hide Secret</span></label>
    <section class="secret-section">
      <button class="fake-button secret-well" onclick="copy('front-element-text', 'secret-text')" tabIndex="0" type="submit">
        <div class="text-container">
          <code class="front-element wrap-and-no-background" id="front-element-text">Copied! </code>
          <code id="secret-text" class="wrap-and-no-background"><%= @plain_text %></code>
        </div>
        <div class="center-vert-container"> <span class="center-vert icon icon-copy blue-icon"> </span></div>
      </button>
    </section>
  </div>
  </div>
</div>

<script>
  function copy(frontId, contentId) {
    /* Get the text field */
    const frontElement = document.getElementById(frontId);
    const link = document.getElementById(contentId).innerText;
    navigator.clipboard.writeText(link);

    frontElement.style.display = 'flex';
    setTimeout(() => {frontElement.style.display = "none";}, 1000)
  }
</script>

lib/otaoto_web/templates/html/secret/gate.html.eex
<div class="section">
  <div class="container">
  <div class="text-center">
    <h3 class="headline">You found a secret!</h3>
    <p class="subtitle">Click the button to see it once and delete it from our service forever</p>
    <%= button "View Secret", method: "post", to: Routes.secret_url(@conn, :show, @slug, key: @key), type: "submit", class: "button button-primary", tabIndex: "0" %>
  </div>
</div>

lib/otaoto_web/templates/html/secret/gone.html.eex
<div class="section">
  <div class="container">
    <div class="text-center">
      <h3 class="headline">There is no secret here.</h3>
      <p class="subtitle">Each link is only useful once. If the link was used, the content is gone forever. It's possible that this link is incorrect and there was never a secret here</p>
      <br/>
      <div>
        <p class="subtitle">Have something to share?</p>
        <%= button "Share a  new Secret", method: "get", to: Routes.secret_path(@conn, :new), class: "button button-primary button-outline", tabIndex: "0", type: "submit" %>
      </div>
    </div>
  </div>
</div>

lib/otaoto_web/templates/html/secret/new.html.eex
<div class="section">
    <div class="container">
        <div class="text-center">
            <h1 class="headline"><strong>Share a secret,</strong> one time and one time only</h1>
            <p class="subtitle">We'll encrypt it and give you a one time link to share with someone else</p>
        </div>
        <div class="row new-secret-form-container">
          <%= form_for @changeset, Routes.secret_path(@conn, :create), [class: "new-secret-form"], fn f -> %>
            <div class='form-group'>
              <div class="column">
                <%= textarea f, :plain_text,
                [class: "form-control secret-textarea",
                required: true] %>
              </div>
            </div>

            <div class="text-center">
                <%= submit "Create a Secret Link", [class: "button button-primary", tabindex: "0"] %>
            </div>
          <% end %>
        </div>
    </div>
</div>
<div class="section">
  <div class="hiw-panel text-center">
    <h1 class="hiw-title">How It Works</h1>
  <div class="row">

      <div class="hiw-step column">
          <h2>Encrypt a Secret</h2>
          <img src="/images/encrypt.svg">
          <p>Text you enter is encrypted with a new random secure key. Otaoto only stores the encrypted content and a hash of the key to help filed the secret later</p>
      </div>
      <div class="hiw-step column">
          <h2>Create a Link</h2>
          <img src="/images/create-link.svg">
          <p>Each link contains two parts, a three word sequence to identify the encrypted secret, and the decryption key.  Otaoto doesn't store that key, the key in your link is the only copy</p>
      </div>
      <div class="hiw-step column">
          <h2>Open the Link</h2>
          <img src="/images/open-link.svg">
          <p>When you visit a link with a secret, Otaoto confirms that there is a secret with that three word sequence and checks to make sure the right key is present</p>
      </div>
      <div class="hiw-step column">
          <h2>Destroy the Secret</h2>
          <img src="/images/burn-secret.svg">
          <p>If all the correct information is present, Otaoto deletes everything from the database, then sends the decrypted text to you. Everything has been deleted, that link will never be usable again</p>
      </div>
  </div>
  </div>
</div>

lib/otaoto_web/templates/html/secret/show.html.eex
<div class="section">
  <div class="container">
  <div class="text-center">
    <h3 class="headline">Your secret</h3>
    <p class="subtitle">Put it somewhere safe! We've already deleted our copy</p>
    <section class="secret-section">
      <button class="secret-well fake-button" onclick="copy('front-element-text', 'secret-text')" tabIndex="0" type="submit">
        <div class="text-container">
          <code class="front-element wrap-and-no-background" id="front-element-text">Copied! </code>
          <code id="secret-text" class="wrap-and-no-background"><%= @plain_text %></code>
        </div>
        <div class="center-vert-container"> <span class="center-vert icon icon-copy blue-icon"> </span></div>
      </button>
    </section>
    <br />
    <div>
      <p class="subtitle">Have something else to share?</p>
      <%= button "Share a  new Secret", method: "get", to: Routes.secret_path(@conn, :new), class: "button button-primary button-outline", tabIndex: "0", type: "submit" %>
    </div>
  </div>
</div>
</div>

<script>
  function copy(frontId, contentId) {
    /* Get the text field */
    const frontElement = document.getElementById(frontId);
    const link = document.getElementById(contentId).innerText;
    navigator.clipboard.writeText(link);

    frontElement.style.display = 'flex';
    setTimeout(() => {frontElement.style.display = "none";}, 1000)
  }
</script>